# Generated by Django 5.0.14 on 2025-11-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('device_type', models.CharField(choices=[('PRODUCTION', 'Production'), ('CONSUMPTION', 'Consumption'), ('STORAGE', 'Storage')], help_text='The type of device (production, consumption, storage)', max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'Offline'), (1, 'Online')], help_text='The status of the device (0 = OFFLINE, 1 = ONLINE)')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
